
package Vistas;

import AccesoData.EspecialidadData;
import Entidades.Especialidad;
import Exceptions.GenericException;
import Utilidades.Utilidades;
import java.awt.Color;
import java.awt.event.KeyEvent;


/**
 *
 * @author MaRio
 */
public class JInternalFrameEditEspecialidad extends javax.swing.JInternalFrame {
    
    private String nombreActual;
    private boolean estadoActual;
    private EspecialidadData especialidadData;
    private Especialidad especialidad =null;

    public JInternalFrameEditEspecialidad() {
        initComponents();
        especialidadData = new EspecialidadData();
        clearLabel();
        cargarComboBox();
        desactivarDesactivarCampos(false);
        disableButtonEdit();
        jLabelRadioButton.setVisible(false);
        jLabelErrorEdit.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonEstado = new javax.swing.JRadioButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jComboBoxEspecialidades = new javax.swing.JComboBox<>();
        jLabelErrorEmptyField = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelRadioButton = new javax.swing.JLabel();
        jLabelErrorEdit = new javax.swing.JLabel();
        jLabelErrorNull = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setText("IdEspecialidad:");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setPreferredSize(new java.awt.Dimension(507, 482));

        jPanel1.setBackground(new java.awt.Color(153, 220, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Editar Especialidad");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setText("Nombre:  ");

        jTextFieldNombre.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jTextFieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusGained(evt);
            }
        });
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel4.setText("Estado");

        jRadioButtonEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEstadoActionPerformed(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonSalir.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jComboBoxEspecialidades.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jComboBoxEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEspecialidadesActionPerformed(evt);
            }
        });

        jLabelErrorEmptyField.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelErrorEmptyField.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorEmptyField.setText("jLabel5");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel5.setText("Elija una Especialidad");

        jLabelRadioButton.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelRadioButton.setText("jLabel6");

        jLabelErrorEdit.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelErrorEdit.setText("jLabel6");

        jLabelErrorNull.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelErrorNull.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorNull.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jButtonEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalir)
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelErrorNull, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxEspecialidades, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelErrorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabelErrorEmptyField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelErrorNull)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelErrorEmptyField)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButtonEstado)
                    .addComponent(jLabelRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabelErrorEdit)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonSalir))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEspecialidadesActionPerformed
        
        try{
            especialidad = (Especialidad)jComboBoxEspecialidades.getSelectedItem();
        
        nombreActual = especialidad.getNombre();
        estadoActual = especialidad.isEstado();
        
        jTextFieldNombre.setText(especialidad.getNombre());
        jRadioButtonEstado.setSelected(especialidad.isEstado());
        labelRadioButton();
         jLabelErrorEdit.setVisible(true);
         disableButtonEdit();
         jLabelErrorNull.setVisible(false);
         desactivarDesactivarCampos(true);
        }catch(NullPointerException e){
            
            jLabelErrorNull.setText("No ha seleccionado ninguna especialidad.");
            clearField();
            jLabelErrorNull.setVisible(true);
        }
    }//GEN-LAST:event_jComboBoxEspecialidadesActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        
        String nombreEspecialidad = jTextFieldNombre.getText();
        boolean estadoEspecialidad = jRadioButtonEstado.isSelected();
        try {
            validateField(nombreEspecialidad);
            
            especialidad = (Especialidad)jComboBoxEspecialidades.getSelectedItem();
        
        especialidad.setNombre(nombreEspecialidad);
        especialidad.setEstado(estadoEspecialidad);
        especialidadData.editarEspecialidad(especialidad);
        
        clearLabel();
        clearField();
        } catch (GenericException ex) {
            showLabelError(ex.getMessage());
        }
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusGained
        clearLabel();
        
    }//GEN-LAST:event_jTextFieldNombreFocusGained

    private void jRadioButtonEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEstadoActionPerformed

        if(estadoActual == jRadioButtonEstado.isSelected()){
            disableButtonEdit();
        }else{
            enableButtonEdit();          
        }
        
        labelRadioButton();
    }//GEN-LAST:event_jRadioButtonEstadoActionPerformed

    private void jTextFieldNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyPressed

        String nombre = jTextFieldNombre.getText();
        int longitudNombre = nombre.length();
        boolean isTrue;
        char teclaPresionada = evt.getKeyChar();
        int count = 0;

        if (teclaPresionada != KeyEvent.VK_BACK_SPACE) {

            nombre = jTextFieldNombre.getText() + teclaPresionada;
            longitudNombre = nombre.length();
            isTrue = nombre.equals(nombreActual) && longitudNombre == nombreActual.length();

        } else {
            //contador para que me permita contar la catidad que presiono la tecla
            //borrar
            count++;
            //variable longitudNombre la cual me sirve para verificar si tiene
            //la misma longitud el nombre acrual y el nombre modificado
            //A la cual le resto uno por que presiono la tecla eliminar
            longitudNombre = nombre.length() - 1;
            //reasigno a la variable nombre con el valor del TextField 
            //concatenado con las teclas presionadas.
            nombre = jTextFieldNombre.getText() + teclaPresionada;
            //armo un substring con lo que contiene la variable nombre 
            // y elimino de la ultima parte de la palabra las veces que preciono
            //la tecla borrar menos uno y de esta manera simulo que lo que escribio
            // y se borro en el textField sea lo correcto.
            nombre = nombre.substring(0, nombre.length() - 1 - count);
            //Por ultino reasigno a la variable isTrue con las respectivas evaluaciones
            isTrue = nombre.equals(nombreActual) && longitudNombre == nombreActual.length();

        }
        //si la variable isTrue es verdadera ejecuta el metodo disableButtonEdit()
        //caso contrario ejecuto el metodo enableButtonEdit()
        if (isTrue) {
            disableButtonEdit();

        } else {
            enableButtonEdit();

        }

    }//GEN-LAST:event_jTextFieldNombreKeyPressed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<Especialidad> jComboBoxEspecialidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelErrorEdit;
    private javax.swing.JLabel jLabelErrorEmptyField;
    private javax.swing.JLabel jLabelErrorNull;
    private javax.swing.JLabel jLabelRadioButton;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonEstado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables

private void cargarComboBox(){
    jComboBoxEspecialidades.addItem(especialidad);
    for(Especialidad iterador : especialidadData.listaDeEspecialidades()){
        
        jComboBoxEspecialidades.addItem(iterador);
    
    }
}

private void desactivarDesactivarCampos(boolean isActivo){
    jTextFieldNombre.setEnabled(isActivo);
    jRadioButtonEstado.setEnabled(isActivo);
}

private void clearField(){
    jTextFieldNombre.setText("");
    jRadioButtonEstado.setSelected(false);
    jLabelRadioButton.setVisible(false);
    jButtonEditar.setEnabled(false);
    jComboBoxEspecialidades.setSelectedIndex(0);
    jLabelErrorEdit.setVisible(false);
    clearLabel();
}
private void clearLabel(){
        jLabelErrorEmptyField.setVisible(false);
        jLabelErrorNull.setVisible(false);
    }
private void validateField(String text) throws GenericException{
    
        if(text.isEmpty() || text.equals("Ej: Odontologia")){
            throw new GenericException("No ingrese campos vacios");
        }
        else if(!Utilidades.contieneSoloLetras(text)){
           
            throw new GenericException("No ingrese numero");
        }
}

private void showLabelError(String message){
        jLabelErrorEmptyField.setVisible(true);
        
        jLabelErrorEmptyField.setText(message);
        
}

private void labelRadioButton(){
    jLabelRadioButton.setVisible(true);
    
    if(jRadioButtonEstado.isSelected()){
        
        jLabelRadioButton.setForeground(new Color(0,102,0));
        jLabelRadioButton.setText("Activar la especialidad.");
    }else{
        jLabelRadioButton.setForeground(Color.RED);
        jLabelRadioButton.setText("Desactivar la especialidad.");
    }
}

private void disableButtonEdit(){
    jButtonEditar.setEnabled(false);
    jLabelErrorEdit.setForeground(Color.RED);
    jLabelErrorEdit.setText("El botón Editar se habilita si modifica algún campo");
}

private void enableButtonEdit(){
    jButtonEditar.setEnabled(true);
    jLabelErrorEdit.setText("");
}

}
